package com.huetoyou.chatexchange.backend;

import com.google.gson.annotations.SerializedName;

/**
 * Chat event generated by a backend
 *
 * The backends generate a stream of events that signal various types of
 * activity in a room. This includes new messages being posted, users entering
 * or leaving the room, replies, etc.
 */
public class Event {

    public static final int EVENT_MESSAGE_POSTED = 1;

    @SerializedName("id") private int mId;

    /**
     * Retrieve the event ID
     */
    public int getId() {
        return mId;
    }

    @SerializedName("event_type") private int mEventType;

    /**
     * Retrieve the event type
     */
    public int getEventType() {
        return mEventType;
    }
}
